#' Draw 3D graphs from tradeStats results using rgl
#'
#' @param stats a data frame generated by tradeStats()
#' @param free.params a vector of length 2, containing the column names for the data to use on the x and z axes
#' @param fixed.params - not yet implemented
#' @param statistics a vector containing the column names to produce graphs for
#' @param title an optional title to be printed above each graph
#' @return invisible -- called for side-effect
#' @examples
#' \dontrun{
#' tradeGraphs (
#'      stats = stats,
#'      free.params = c("Param.indicator.1.nFast", "Param.indicator.2.nSlow"),
#'      fixed.params = NULL,
#'      statistics = c("Net.Trading.PL", "maxDrawdown", "Avg.Trade.PL", "Num.Trades")
#'      title = 'Luxor'
#' )
#' }
#' @export

tradeGraphs <- function(stats, free.params, fixed.params = NULL, statistics, title = NULL)
{
        # TODO: implement fixed.params
        # TODO: fix axes to use non scientific notation
        # TODO: fix use of full rainbow for small fractions (eg. Profit.Factor, now only uses red)

	if(!require(rgl, quietly=TRUE))	stop('The "rgl" package is required to use this function')

        if(missing(stats))      stop('stats undefined')

        if(missing(free.params))        stop('free.params undefined')
        if(length(free.params) != 2)    stop('free.params must be a vector of length 2')

        if(missing(statistics))         stop('must specify at least one statistics column to draw graph')

        # derive sizes from free parameters

        range.free.param.1 = range(stats[[free.params[1]]])
        min.free.param.1 = range.free.param.1[1]
        max.free.param.1 = range.free.param.1[2]

        range.free.param.2 = range(stats[[free.params[2]]])
        min.free.param.2 = range.free.param.2[1]
        max.free.param.2 = range.free.param.2[2]

        nrows = range.free.param.1[2] - range.free.param.1[1] + 1
        ncols = range.free.param.2[2] - range.free.param.2[1] + 1

        # draw graph for each statistic

        for(statistic in statistics)
        {
                # fill data matrix

                graph.data <- matrix(NA, nrows, ncols)

                for(i in 1:nrow(stats[free.params[1]]))
                {
                        free.param.1 = stats[[free.params[1]]][i]
                        free.param.2 = stats[[free.params[2]]][i]

                        graph.data[free.param.1 - min.free.param.1 + 1, free.param.2 - min.free.param.2 + 1] = stats[[statistic]][i]
                }

                # set up color vector

                range.statistic = range(stats[[statistic]])
                span.statistic = range.statistic[2] - range.statistic[1] + 1

                colors <- rainbow(span.statistic)[graph.data - range.statistic[1] + 1]

                # draw graph

                rgl.open()
                rgl.surface(x=min.free.param.1:max.free.param.1, z=min.free.param.2:max.free.param.2, y=graph.data, color=colors)
                rgl.planes(a=1, alpha=0.7)

                aspect3d(1,1,1)
                axes3d()
                title3d(title, NULL, free.params[1], statistic, free.params[2])
        }
}

###############################################################################
# R (http://r-project.org/) Quantitative Strategy Model Framework
#
# Copyright (c) 2009-2011
# Peter Carl, Dirk Eddelbuettel, Brian G. Peterson, Jeffrey Ryan, Garrett See, and Joshua Ulrich 
#
# This library is distributed under the terms of the GNU Public License (GPL)
# for full details see the file COPYING
#
# $Id: wrapup.R 849 2011-11-16 17:47:25Z gsee $
#
###############################################################################
